import os
import shutil
import uuid

from typing import Optional

from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import JSONResponse, FileResponse

from server.config import UPLOAD_DIR
from server.services.feedback_generator import run_feedback_pipeline

router = APIRouter(prefix="/feedback", tags=["feedback"])

@router.post("/generate", summary="Generate multi-phase feedback for a UI design")
async def generate_feedback(
    ui_image: UploadFile = File(...),
    audit_json: Optional[UploadFile] = File(None)
):
    """
    Accepts an image and an optional JSON audit file, runs the multi-phase Gemini/YOLO pipeline,
    and returns annotated image urls plus a text-to-image prompt.
    """
    try:
        # Save uploaded image
        img_id = uuid.uuid4().hex[:8]
        img_ext = os.path.splitext(ui_image.filename)[1] if ui_image.filename else ".png"
        img_path = os.path.join(UPLOAD_DIR, f"{img_id}_ui{img_ext}")
        
        with open(img_path, "wb") as f:
            shutil.copyfileobj(ui_image.file, f)
            
        json_path = ""
        # Save uploaded JSON if provided
        if audit_json:
            json_path = os.path.join(UPLOAD_DIR, f"{img_id}_audit.json")
            with open(json_path, "wb") as f:
                shutil.copyfileobj(audit_json.file, f)

        # Execute pipeline
        # (Assuming you put best3.pt in server/weights/best3.pt, else default to yolov8n.pt)
        yolo_path = os.path.join("server", "weights", "best3.pt")
        
        result = run_feedback_pipeline(
            ui_image_path=img_path, 
            json_file_path=json_path,
            yolo_model_path=yolo_path
        )
        
        if "error" in result:
             raise HTTPException(status_code=500, detail=result["error"])

        return result
        
    except Exception as e:
        print(f"Error in generate_feedback: {e}")
        return JSONResponse(status_code=500, content={"error": str(e)})

@router.get("/report/{report_id}", summary="Get annotated feedback image")
async def get_feedback_image(report_id: str):
    """Serve the annotated images generated by the pipeline"""
    # report_id includes the phase, e.g. "uuid_p1"
    report_path = os.path.join(UPLOAD_DIR, f"{report_id}.jpg")

    if os.path.exists(report_path):
        return FileResponse(report_path, media_type="image/jpeg")

    return JSONResponse(status_code=404, content={"error": "Image not found"})
