import os
from typing import Any, Dict

def generate_markdown_report(audit_result: Dict[str, Any]) -> str:
    """
    Generates a structured Markdown report from AI audit results.
    """
    meta = audit_result.get("meta", {})
    summary = audit_result.get("summary", {})
    violations = audit_result.get("violations", [])
    llm_analysis = audit_result.get("llm_analysis", "No AI analysis available.")

    report = []
    report.append(f"# 🔍 Smart UI Audit Report")
    report.append(f"**Timestamp:** {meta.get('timestamp', 'N/A')}")
    report.append(f"**Profile:** {meta.get('profile', 'universal').upper()}")
    report.append(f"**Target:** {meta.get('figma_url', 'Direct Upload')}")
    report.append(f"\n---\n")

    report.append(f"## 📊 Summary")
    report.append(f"- **Overall Accuracy:** {summary.get('score', 0)}%")
    report.append(f"- **Total Violations Detected:** {summary.get('violations', 0)}")
    report.append(f"\n")

    report.append(f"## 🤖 AI Consultant Analysis")
    report.append(f"> {llm_analysis}")
    report.append(f"\n")

    report.append(f"## 📋 Detailed Violations")
    if not violations:
        report.append("✅ No rule violations detected in this session.")
    else:
        for v in violations:
            report.append(f"### ❌ {v.get('title', 'Unknown Rule')}")
            report.append(f"- **Description:** {v.get('description', 'N/A')}")
            
            elem = v.get('element_info', {})
            if elem:
                report.append(f"- **Element Type:** {elem.get('type', 'N/A')}")
                report.append(f"- **Location (BBox):** {elem.get('bbox')}")
            report.append("\n")

    report.append(f"\n---\n")
    report.append(f"*Report generated by Smart UI Auditor — AI Powered UI/UX Analyst*")

    return "\n".join(report)
